datas.json

The following request: https://discord.com/channels/958463934313144401/1131923981260292207
The colors has been corrected.

Singe moomin

---

datas.json

The following request: https://discord.com/channels/958463934313144401/1131932662878175253
The colors has been corrected.

Ikea blahai

---

datas.json

The following request: https://discord.com/channels/958463934313144401/1131689376162795712
The colors has been corrected.
Need to be voted.

Norway viking rematch

---

datas.json

Removed  blåhaj, no vote from sweden to have it, cluttering

Remove blåhaj datas.json

---

datas.json

Denish comunity would like these 2 images please!

Lego Art (50 Votes) & John Dillermand (19 votes)

---

datas.json

changed the blue color to the dark blue

Blue corection

---

datas.json

Added some shading to the mountain. Flowers on the grass fields. Shifted the text slightly to the right, and made some smaller modifications to the viking ship. This also incorporates Zombey (the purple guy) with the ship.
The initial plan was to move the purple guy as was talked about in #20, however it seems that Denmark has now filled in this area.
I'm not sure if it would be more correct to have the purple guy in the template or not. At the moment I added him into the template, but that can be changed.
This is what the end result would look like:

Update the norway viking rematch artwork

---

datas.json

Request here: https://discord.com/channels/958463934313144401/1132080273673175171
Final output:

Midsommar green

---

datas.json

Reverts MeblIkea/NordicPlace#24

Revert "Midsommar green"

---

datas.json

I've added it at the same time where you added it.
Had to remove your, because it passed in front of the bridges, and there were no vingegaard.
Sorry

Added at the exact same time, sorry :/

---

datas.json

Updated Lego Benny to full body. Moved Polandball up and right to be out of way.
Lego community discord wants a full body Benny with updated shading. Polandball gets moved to be beside Benny. Also I have no idea how the coordinates work so someone double check it for me please, sorry.

Update Lego Benny to full body

---

datas.json

I think this moves them to the right place? Apologies if this goes wrong again.
#50

Moved Lego and Polandball

---

datas.json

The demons are being relocated left of kungen to make space, please just push this change through so that people stop rebuilding

Remove demons from data.json

---

datas.json

This reverts commit b43e5998e3d1dab4dad7f52ac0aea518e3bc29bb.

Revert "viking"

---

datas.json

Added heart for Maryland flag

---

datas.json

Update Maryland Flag to use newly released colors

Update Maryland Flag to use newly released colors

---

datas.json

https://discord.com/channels/958463934313144401/1131607693015130272/1132739926295859251

 remove legs vikings

---

datas.json

This reverts commit a77af341934a1dc6a22824192cf1cfb0f8dc66e7.

Revert "coats"

---

datas.json

Fish for safekeeping

---

datas.json

Corrected colors. The previous fish was approved over night, but this color corrected one is yet to be approved in suomi-poll.

Fish with corrected colors

---

datas.json

Fixed sunset colors and modified vikingship gif

New url for r/Norge sunset and ship

---

datas.json

Added Old Bay can to Maryland Flag:

Maryland Flag: Add Old Bay

---

datas.json

Reverts MeblIkea/NordicPlace#123

Revert "norge update"
